# .render.yaml for deploying Flask app on Render
services:
  - type: web
    name: food-restriction-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
